### DISCUSSION TITLE
Issue with webauthn_verify_attestation_response Returning 401 in Android

### DISCUSSION THREAD

**Discussion by krunaldaveazilen** [teamhanko/hanko#2061] [Q&A] [answered]
Hi Team,

I'm testing the Flow API for registration on native Android. I’ve set up the Hanko server locally and exposed the backend port using ngrok. I also added the Android key hash under:

yaml
```

webauthn:
  relying_party:
    origins:
      - "http://localhost:8888"
      - "android:apk-key-hash:TyBHH9maupZHjVknwsim6o7SjRTAtqI5mZ-jTUc9-hE"
```
The registration flow completes successfully until the final step, webauthn_verify_attestation_response, which consistently returns a 401 Unauthorized error.

Request (cURL)
```

curl --location 'https://e016-14-98-189-6.ngrok-free.app/registration?action=webauthn_verify_attestation_response%40525a5c2e-15e7-4e90-9230-f0311dce5cb1' \
--header 'Content-Type: application/json' \
--header 'Cookie: hanko=...' \
--data '{ "input_data": { "public_key": { ... } }, "csrf_token": "qZ8sJc0fzmOQmTcVuQocoE1gxyy4DfEz" }'
```
Response

```
{
  "name": "success",
  "status": 401,
  "error": {
    "code": "passkey_invalid",
    "message": "The passkey is invalid."
  }
}
```
Note:
I'm executing all steps via Postman. After receiving the public key in webauthn_generate_creation_options, I use that value to get the PublicKeyCredentialAttestationResponse from the mobile app and pass it to webauthn_verify_attestation_response via Postman.

Any insights on why the passkey might be considered invalid?
