### DISCUSSION TITLE
Quicksetup with docker, fails with "create jwk manager"

### DISCUSSION THREAD

**Discussion by kr2792** [teamhanko/hanko#536] [Q&A] [answered]
Hi

I'm trying to follow the tutorial for getting started.

I've got the following config.yaml file:

```
database:
  user: hanko
  password: testing
  host: host.docker.internal # change this if the DB is not running on localhost, esp. in a production setting
  port: 3306
  database: hanko
  dialect: mysql # depending on your choice of DB: postgres, mysql
secrets:
  keys:
    - my-32-character-ultra-secure-and-ultra-long-secret
webauthn:
  relying_party:
    id: "localhost"
    display_name: "Hanko Authentication Service"
    origin: "http://localhost"
server:
  public:
    cors:
      enabled: true
      allow_credentials: true
      allow_origins:
        - "https://localhost"
passcode:
  email:
    from_address: no-reply@example.com
    from_name: Example Application
  smtp:
    host: localhost
    port: 2500
service:
  name: Example Authentication Service
```

I had to change host in database to *host.docker.internal* instead of localhost, because the migration command couldn't find it otherwise. The migration succeeds with, and I can see the database and tables in the database. Then the next command fails:

`docker run --mount type=bind,source=C:\mypath\to\config.yaml,target=/config/config.yaml -p 8000:8000 -it ghcr.io/teamhanko/hanko:main serve public
`
```
2023/01/27 23:15:17 Using config file: ./config/config.yaml
panic: failed to create jwk manager: failed to get jwk: mysql select one: sql: no rows in result set

goroutine 16 [running]:
github.com/teamhanko/hanko/backend/server.NewPublicRouter(0x13df640, {0x7ff0da37a998, 0xc00000f0b0})
        /workspace/server/public_router.go:40 +0x170e
github.com/teamhanko/hanko/backend/server.StartPublic(0x13df640, 0x0, {0x7ff0da37a998, 0xc00000f0b0})
        /workspace/server/server.go:11 +0x6c
created by github.com/teamhanko/hanko/backend/cmd/serve.NewServePublicCommand.func1
        /workspace/cmd/serve/public.go:29 +0x185
PS C:\Users\Krist\OneDrive\Desktop\projects\Hanko>
```

I can see that the table jwks is empty, if that helps. Anyone know or have a hint to what my problem could be?
