### ISSUE TITLE
Email security notifications

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#1030]
Currently, Hanko backend only sends emails for passcode authentication.

Add a new config option to enable / disable account security notifications.

If enabled, send security notification emails to the user's primary email address on

- Password changed
- Email address added
- Primary email address changed (use primary email **before the change**)
- Passkey created

**Comment by irby** [comment]
Would we want to configure each of these scenarios individually?

**Comment by irby** [comment]
@FlxMgdnz ill take on this item

**Comment by FlxMgdnz** [comment]
> @FlxMgdnz Would we want to configure each of these scenarios individually?

@irby I think it would be better to be able to toggle each warning individually, yes.

**Comment by prashantug21** [comment]
@FlxMgdnz Is this issue available?

**Comment by Fer-Win** [comment]
@FlxMgdnz If no is currently working on it or you would want someone else to work on it. Let me try it please..Assign it to me...

**Comment by Fer-Win** [comment]
@irby ok fine, let me know if any other issue opens up

**Comment by irby** [comment]
@FlxMgdnz I'm assuming emails sent out should be recorded in an audit log, correct?

Do we want to refactor the SMTP settings? Currently, these configuration settings are setup under passcode, but obviously as we include security notifications these will no longer only apply to passcodes.

**Comment by FlxMgdnz** [comment]
@irby yes we should log the emails.

SMTP settings refactoring makes sense imho.

**Comment by irby** [comment]
@FlxMgdnz It'll make sense to break out the SMTP settings refactor into its own PR. Do you want me to create an issue for this change, or can I link it to this issue?

**Comment by FlxMgdnz** [comment]
Right, that makes sense. Linking to this issue/comment should be sufficient. Thanks @irby !

**Comment by irby** [comment]
I'm willing to take myself off this ticket. I haven't actioned on this in some time. @FlxMgdnz @wrobat

**Comment by Aashana101** [comment]
@FlxMgdnz kindly assign this to me

**Comment by FlxMgdnz** [comment]
@irby any chance you can pick this back up?

**Comment by irby** [comment]
@FlxMgdnz Sure thing. Let me sync up my fork with the latest repo and I'll take a look again at this.

**Comment by irby** [comment]
Hey @FlxMgdnz wanted to get clarity on some requirements. For the following:

- Email address added
  Do we notify the email address being added and the primary email address?
- Primary email address changed (use primary email before the change)
  Are we only sending this email to the old primary email?

For each template, we've agreed we want them to be enabled individually. I'm thinking the config could look like this

```yaml
security_notifications:
  notification_types:
    primary_email_updated:
      enabled: true
    email_added:
      enabled: true
    password_updated:
      enabled: true
    passkey_added:
      enabled: true
  sender:
    from_address: "security@hanko.com"
    from_name: "Hanko Security"
```

Does this config seem fine to you? Any changes you'd like to make?

For all the notification types, I will default them to false. Unless you feel otherwise, I do not think we need to add any validation to the sender configuration.

**Comment by FlxMgdnz** [comment]
Hey @irby, thanks for your input.

> * Email address added
>   Do we notify the email address being added and the primary email address?

I think it’s enough to notify the primary email, since that’s basically the reason we added the primary email logic in the first place.

> * Primary email address changed (use primary email before the change)
>   Are we only sending this email to the old primary email?

Yes, IMO that should be sufficient, otherwise you’d end up getting the same email twice.

The proposed config looks good to me. I’d just suggest using the same sender (`from_address` / `from_name`) as for passcode emails; no need to introduce a new one for security notifications, don't you think?

I’d also default the notifications to `true`.

@FreddyDevelop any comments?

**Comment by irby** [comment]
@FlxMgdnz Defaulting to true is fine. Just note the side effect is if folks upgrade the backend it will automatically turn on notifications. 

And I'm ok with using the same sender as for the standard emails, that'll simplify the config a little bit. If, down the line, we want to add that as additional configuration, it should be easy to add it in.

**Comment by irby** [comment]
@FlxMgdnz @FreddyDevelop Here is the tentative security notification text. Please let me know if you want any wording change.

```yaml
# backend/mail/locales/security-notifications.en.yaml
password_update_text:
  description: ""
  other: "The password for your {{ .ServiceName }} account has been successfully updated."
email_subject_password_update:
  description: ""
  other: "Your {{ .ServiceName }} account password has been updated"

primary_email_update_text:
  description: ""
  other: "The primary email address for your {{ .ServiceName }} account has been successfully updated from {{ .OldEmailAddress }} to {{ .NewEmailAddress }}."
email_subject_primary_email_update:
  description: ""
  other: "Your {{ .ServiceName }} primary email address has been updated"

email_create_text:
  description: ""
  other: "The email address {{ .NewEmailAddress }} has been successfully added to your {{ .ServiceName }} account."
email_subject_email_create:
  description: ""
  other: "A new email address has been registered to your {{ .ServiceName }} account"


passkey_create_text:
  description: ""
  other: "Your {{.ServiceName}} account has been registered with a new passkey."
email_subject_passkey_create:
  description: ""
  other: "A new passkey has been registered to your {{ .ServiceName }} account"
```

**Comment by FlxMgdnz** [comment]
Hey @irby -- first of all, sorry for the late reply. And thank you for pushing this forward.

I think your texts are fine, just a few thoughts:

- Since `ServiceName` is already the sender of the email, I tend to want to remove it from the email subject for clarity.
- The naming of the keys should ideally follow the schema of the existing keys for the Flow API (i.e., removing "email_" before "subject")
- I feel like we should change the tone of the emails a bit to be less enthusiastic by removing the word "successfully"
- Also, we should add more notifications (sorry I missed that before) for
  - email deleted
  - 2FA added 
  - 2FA deleted

```yaml
# backend/mail/locales/security-notifications.en.yaml
password_update_text:
  description: ""
  other: "The password for your {{ .ServiceName }} account has been updated."
subject_password_update:
  description: ""
  other: "Your password has been updated"

primary_email_update_text:
  description: ""
  other: "The primary email address for your {{ .ServiceName }} account has been updated from {{ .OldEmailAddress }} to {{ .NewEmailAddress }}."
subject_primary_email_update:
  description: ""
  other: "Your primary email address has been updated"

email_create_text:
  description: ""
  other: "The email address {{ .NewEmailAddress }} has been added to your {{ .ServiceName }} account."
subject_email_create:
  description: ""
  other: "A new email address has been registered"

passkey_create_text:
  description: ""
  other: "Your {{.ServiceName}} account has been registered with a new passkey."
subject_passkey_create:
  description: ""
  other: "A new passkey has been registered"
```

**Comment by irby** [comment]
Hey @FlxMgdnz could you provide me with the recommended text for the email delete, 2FA create, 2FA removed templates?

Can multiple 2FA methods be added to the account? What counts as a 2FA creation? Security keys and authenticator added? Should we say MFA instead of 2FA?

**Comment by FlxMgdnz** [comment]
Hey @irby,

Correct, 2nd factors in Hanko are security keys and a TOTP authenticator app. While users can add multiple security keys, only one authenticator app can be configured per account. I think we should trigger a notification email on creation of the first 2nd factor and on deletion of the last, i.e. "2FA enabled" and "2FA disabled".

I prefer the acronym "2FA" over "MFA" in user-facing texts.

```yaml
mfa_enabled_text:
  description: ""
  other: "Two-factor authentication has been successfully enabled for your {{ .ServiceName }} account."
subject_mfa_enabled:
  description: ""
  other: "Two-factor authentication enabled"

mfa_disabled_text:
  description: ""
  other: "Two-factor authentication has been disabled for your {{ .ServiceName }} account."
subject_mfa_disabled:
  description: ""
  other: "Two-factor authentication disabled"
```
