### ISSUE TITLE
Not proceed from `/initialize` method called on FQDN and TLS

### ISSUE THREAD

**Issue by letusfly85** [teamhanko/hanko#715]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

Hi, thank you for great solution.

We're now trying hosting this service on our AWS.
For the first step, we tried serving `frontend/examples/react` by using `docker-compose`.

Especially, we want to try webauthn processes.

But when we service processes by using `docker-compose.yml` and Let's Encrypt and several reverse proxies,
we cannot proceed to some steps after `/initialize` POST method called, the method returns 200OK, but it doesn't proceed to next steps..

On localhost, it works perfectly.
But on FQDN and TLS environment, it doesn't work.

Is there any way to proceed...? or should we create our own frontend processes from scratch..?

## 1. replace hostnames on yml

`cat -p deploy/docker-compose/config.yaml`

```yaml
database:
  user: hanko
  password: hanko
  host: postgresd
  port: 5432
  dialect: postgres
passcode:
  email:
    from_address: no-reply@hanko.io
  smtp:
    host: "mailslurper"
    port: "2500"
secrets:
  keys:
    - **************************
service:
  name: Hanko Authentication Service
server:
  public:
    cors:
      enabled: true
      allow_credentials: true
      allow_origins:
        - '*'
webauthn:
  relying_party:
    origin: "https://MY_HOST_NAME"
session:
  cookie:
    secure: false
 ```

## 2. run processes

```bash
docker compose -f deploy/docker-compose/quickstart.yaml  -p "hanko-quickstart" up --build
```

### Logs

```Shell
There are no logs on Chrome/Safari inspectors after `/initialize` method.`
```

### Hanko Version

0fca4c0b753059d4ebd97e08f5a9d9dc9e546019

### OS

Linux

### OS Version

Ubuntu 20.04 TLS

### Browser Version

Chrome  112.0.5615.49（Official Build） （x86_64）

### Environment

Docker Compose
